services:
  rsi-killer-binance-eth:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-eth
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "ETH/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 0.02
      POSICAO: 0.01
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 30
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10

  rsi-killer-binance-sol:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-sol
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "SOL/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 0.20
      POSICAO: 0.15
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10

  rsi-killer-binance-doge:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-doge
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "DOGE/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 1000.00
      POSICAO: 850.00
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-link:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-link
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "LINK/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 2
      POSICAO: 3
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-avax:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-avax
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "AVAX/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 5
      POSICAO: 3
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-arb:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-arb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "ARB/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 350
      POSICAO: 200
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-op:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-op
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "OP/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 350
      POSICAO: 200
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-apt:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-apt
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "APT/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 30
      POSICAO: 20
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-inj:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-inj
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "INJ/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 9
      POSICAO: 7
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10
  
  rsi-killer-binance-near:
    image: rsi-killer-binance:latest
    container_name: rsi-killer-binance-near
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SYMBOL: "NEAR/USDT"
      LOSS: -1
      TARGET: 2
      POSICAO_MAX: 35
      POSICAO: 20
      RSI_SOBRECOMPRA: 65
      RSI_SOBREVENDA: 35
      BB_LENGTH: 20
      BB_STD: 2
      THRESHOLD: 0.0015
      LEVERAGE: 10